const { listVoices, Communicate } = require('edge-tts-universal');
const googleTTS = require('google-tts-api');
const { createAudioResource, StreamType } = require('@discordjs/voice');
const { Readable } = require('stream');
const { spawn } = require('child_process');
const axios = require('axios');
const path = require('path');
const fs = require('fs');

let edgeVoices = [];

async function init() {
    try {
        edgeVoices = await listVoices();
        console.log(`[TTS Provider] Loaded ${edgeVoices.length} Edge voices.`);
    } catch (e) {
        console.error("Failed to load Edge voices:", e);
    }
}

function getEdgeVoices() {
    return edgeVoices;
}

async function getAudioResource(text, provider, voiceKey) {
    console.log(`[TTS Debug] Provider: ${provider}, Voice: ${voiceKey}, Text: "${text}"`);

    if (provider === 'google') {
        const voiceOptions = require('./voiceConstants');
        const voiceConfig = voiceOptions[voiceKey] || voiceOptions['en-US'];

        console.log(`[TTS Debug] Google Config:`, voiceConfig);
        const url = googleTTS.getAudioUrl(text, {
            lang: voiceConfig.lang,
            slow: false,
            host: voiceConfig.host,
        });
        console.log(`[TTS Debug] Google URL: ${url}`);
        
        try {
            const response = await axios.get(url, { responseType: 'stream' });
            return createAudioResource(response.data, { inputType: StreamType.Arbitrary });
        } catch (error) {
            console.error("Failed to fetch Google TTS audio from URL:", error.message);
            throw new Error("Could not retrieve Google TTS audio.");
        }

    } else if (provider === 'edge') {
        const comm = new Communicate(text, { voice: voiceKey });
        
        const stream = new Readable({ read() {} });
        let audioGenerated = false;

        (async () => {
            try {
                for await (const chunk of comm.stream()) {
                    if (chunk.type === 'audio') {
                        audioGenerated = true;
                        stream.push(chunk.data);
                    }
                }

                if (!audioGenerated) {
                    throw new Error("No audio was generated by the Edge TTS service, which may be temporarily unavailable.");
                }

                stream.push(null); 
            } catch (err) {
                console.error("Edge TTS Stream Error:", err);
                // Forward the error to the stream to be caught by the player
                stream.destroy(err);
            }
        })();

        return createAudioResource(stream, { inputType: StreamType.Arbitrary });
    
    } else if (provider === 'piper') {
        return new Promise((resolve, reject) => {
            const piperPath = 'piper'; 
            const botRoot = path.resolve(__dirname, '..');
            
            // Aggressive Fix for the 'onnx' bug
            let effectiveVoiceKey = voiceKey;
            if (!effectiveVoiceKey || effectiveVoiceKey === 'onnx' || effectiveVoiceKey === 'undefined') {
                effectiveVoiceKey = 'models/en_US-amy-medium.onnx';
                console.log(`[Piper Debug] Invalid voiceKey ("${voiceKey}") detected. Forcing fallback to: ${effectiveVoiceKey}`);
            }

            const modelPath = path.isAbsolute(effectiveVoiceKey) ? effectiveVoiceKey : path.resolve(botRoot, effectiveVoiceKey);
            
            console.log(`[Piper Debug] Attempting to spawn Piper:`);
            console.log(`  - Command: ${piperPath}`);
            console.log(`  - Model: ${modelPath}`);
            console.log(`  - Text: "${text.substring(0, 30)}..."`);

            if (!fs.existsSync(modelPath)) {
                console.error(`[Piper Error] Model file NOT found at: ${modelPath}`);
                return reject(new Error(`Piper model not found at: ${modelPath}`));
            }

            const piperProcess = spawn(piperPath, [
                '--model', modelPath,
                '--output_file', '-'
            ]);

            let dataCount = 0;
            piperProcess.stdout.on('data', (chunk) => {
                dataCount += chunk.length;
                if (dataCount > 0 && dataCount < 1000) { // Log once when data starts
                    console.log(`[Piper Debug] Started receiving audio data (${chunk.length} bytes received so far)`);
                }
            });

            piperProcess.stdin.write(text);
            piperProcess.stdin.end();

            piperProcess.stderr.on('data', (data) => {
                const msg = data.toString().trim();
                if (msg) console.log(`[Piper Process Log] ${msg}`);
            });

            piperProcess.on('close', (code) => {
                console.log(`[Piper Debug] Process closed with code: ${code}. Total audio data: ${dataCount} bytes.`);
                if (dataCount === 0) {
                    console.error(`[Piper Warning] Piper produced ZERO bytes of audio data. Check Piper logs above.`);
                }
            });

            piperProcess.on('error', (err) => {
                console.error(`[Piper TTS Error] Failed to start Piper process: ${err.message}`);
                reject(new Error("Failed to start Piper TTS. Please ensure 'piper' is installed and in your PATH."));
            });

            const stream = piperProcess.stdout;
            
            resolve(createAudioResource(stream, { 
                inputType: StreamType.Arbitrary 
            }));
        });
    }

    throw new Error("Unknown provider");
}

module.exports = { init, getEdgeVoices, getAudioResource };
