const { listVoices, Communicate } = require('edge-tts-universal');
const googleTTS = require('google-tts-api');
const { createAudioResource, StreamType } = require('@discordjs/voice');
const { Readable } = require('stream');
const axios = require('axios');

let edgeVoices = [];

async function init() {
    try {
        edgeVoices = await listVoices();
        console.log(`[TTS Provider] Loaded ${edgeVoices.length} Edge voices.`);
    } catch (e) {
        console.error("Failed to load Edge voices:", e);
    }
}

function getEdgeVoices() {
    return edgeVoices;
}

async function getAudioResource(text, provider, voiceKey) {
    console.log(`[TTS Debug] Provider: ${provider}, Voice: ${voiceKey}, Text: "${text}"`);

    if (provider === 'google') {
        const voiceOptions = require('./voiceConstants');
        const voiceConfig = voiceOptions[voiceKey] || voiceOptions['en-US'];

        console.log(`[TTS Debug] Google Config:`, voiceConfig);
        const url = googleTTS.getAudioUrl(text, {
            lang: voiceConfig.lang,
            slow: false,
            host: voiceConfig.host,
        });
        console.log(`[TTS Debug] Google URL: ${url}`);
        
        try {
            const response = await axios.get(url, { responseType: 'stream' });
            return createAudioResource(response.data, { inputType: StreamType.Arbitrary });
        } catch (error) {
            console.error("Failed to fetch Google TTS audio from URL:", error.message);
            throw new Error("Could not retrieve Google TTS audio.");
        }

    } else if (provider === 'edge') {
        const comm = new Communicate(text, { voice: voiceKey });
        
        const stream = new Readable({ read() {} });
        let audioGenerated = false;

        (async () => {
            try {
                for await (const chunk of comm.stream()) {
                    if (chunk.type === 'audio') {
                        audioGenerated = true;
                        stream.push(chunk.data);
                    }
                }

                if (!audioGenerated) {
                    throw new Error("No audio was generated by the Edge TTS service, which may be temporarily unavailable.");
                }

                stream.push(null); 
            } catch (err) {
                console.error("Edge TTS Stream Error:", err);
                // Forward the error to the stream to be caught by the player
                stream.destroy(err);
            }
        })();

        return createAudioResource(stream, { inputType: StreamType.Arbitrary });
    }
    throw new Error("Unknown provider");
}

module.exports = { init, getEdgeVoices, getAudioResource };
