const { listVoices, Communicate } = require('edge-tts-universal');
const googleTTS = require('google-tts-api');
const { createAudioResource, StreamType } = require('@discordjs/voice');
const { Readable } = require('stream');
const { spawn } = require('child_process');
const axios = require('axios');
const path = require('path');
const fs = require('fs');

let edgeVoices = [];

async function init() {
    try {
        edgeVoices = await listVoices();
        console.log(`[TTS Provider] Loaded ${edgeVoices.length} Edge voices.`);
    } catch (e) {
        console.error("Failed to load Edge voices:", e);
    }
}

function getEdgeVoices() {
    return edgeVoices;
}

async function getAudioResource(text, provider, voiceKey) {
    console.log(`[TTS Debug] Provider: ${provider}, Voice: ${voiceKey}, Text: "${text}"`);

    if (provider === 'google') {
        const voiceOptions = require('./voiceConstants');
        const voiceConfig = voiceOptions[voiceKey] || voiceOptions['en-US'];

        console.log(`[TTS Debug] Google Config:`, voiceConfig);
        const url = googleTTS.getAudioUrl(text, {
            lang: voiceConfig.lang,
            slow: false,
            host: voiceConfig.host,
        });
        console.log(`[TTS Debug] Google URL: ${url}`);
        
        try {
            const response = await axios.get(url, { responseType: 'stream' });
            return createAudioResource(response.data, { inputType: StreamType.Arbitrary });
        } catch (error) {
            console.error("Failed to fetch Google TTS audio from URL:", error.message);
            throw new Error("Could not retrieve Google TTS audio.");
        }

    } else if (provider === 'edge') {
        const comm = new Communicate(text, { voice: voiceKey });
        
        const stream = new Readable({ read() {} });
        let audioGenerated = false;

        (async () => {
            try {
                for await (const chunk of comm.stream()) {
                    if (chunk.type === 'audio') {
                        audioGenerated = true;
                        stream.push(chunk.data);
                    }
                }

                if (!audioGenerated) {
                    throw new Error("No audio was generated by the Edge TTS service, which may be temporarily unavailable.");
                }

                stream.push(null); 
            } catch (err) {
                console.error("Edge TTS Stream Error:", err);
                // Forward the error to the stream to be caught by the player
                stream.destroy(err);
            }
        })();

        return createAudioResource(stream, { inputType: StreamType.Arbitrary });
    
    } else if (provider === 'piper') {
        return new Promise((resolve, reject) => {
            // Path to your Piper executable. Adjust if it's not in global PATH.
            const piperPath = 'piper'; 
            
            // Assume voiceKey is the full path to the .onnx model, e.g., 'data/piper_models/en_US-amy-medium.onnx'
            // Check if model exists
            if (!fs.existsSync(voiceKey)) {
                return reject(new Error(`Piper model not found at: ${voiceKey}`));
            }

            // Spawn Piper process
            // Usage: echo "text" | piper --model model.onnx --output_raw
            const piperProcess = spawn(piperPath, [
                '--model', voiceKey,
                '--output_raw'
            ]);

            piperProcess.stdin.write(text);
            piperProcess.stdin.end();

            piperProcess.on('error', (err) => {
                console.error(`[Piper TTS Error] Failed to start Piper: ${err.message}`);
                reject(new Error("Failed to start Piper TTS. Is it installed?"));
            });

            const stream = piperProcess.stdout;
            
            // Piper raw output is usually 16-bit mono PCM. 
            // We can pipe it directly or let Discord.js guess. 
            // Often specifying inputType: StreamType.Raw is safer if we knew the specific details,
            // but Arbitrary usually works if the stream has enough data.
            // For raw PCM, we might need to wrap it in a ffmpeg transcoder if Discord doesn't like it directly,
            // but let's try direct first.
            
            resolve(createAudioResource(stream, { 
                inputType: StreamType.Arbitrary 
            }));
        });
    }

    throw new Error("Unknown provider");
}

module.exports = { init, getEdgeVoices, getAudioResource };
