module.exports = {
    // Free Google Translate (Legacy)
    'en-US': { label: 'en-US (Google Translate)', lang: 'en', host: 'https://translate.google.com' },
    'en-GB': { label: 'en-GB (Google Translate)', lang: 'en', host: 'https://translate.google.co.uk' },
    'en-AU': { label: 'en-AU (Google Translate)', lang: 'en', host: 'https://translate.google.com.au' },
    'en-IN': { label: 'en-IN (Google Translate)', lang: 'en', host: 'https://translate.google.co.in' },
    'es-ES': { label: 'es-ES (Google Translate)', lang: 'es', host: 'https://translate.google.com' },
    'fr-FR': { label: 'fr-FR (Google Translate)', lang: 'fr', host: 'https://translate.google.com' },
    'ja-JP': { label: 'ja-JP (Google Translate)', lang: 'ja', host: 'https://translate.google.com' },
    'de-DE': { label: 'de-DE (Google Translate)', lang: 'de', host: 'https://translate.google.com' },
    'pt-BR': { label: 'pt-BR (Google Translate)', lang: 'pt', host: 'https://translate.google.com' },

    // --- Google Cloud (Official) ---
    'en-US-Studio-O': { label: 'en-US-Studio-O', gcloud: true },
    'en-US-Chirp3-HD-Aoede': { label: 'en-US-Chirp3-HD-Aoede', gcloud: true },
    'en-US-Chirp3-HD-Charon': { label: 'en-US-Chirp3-HD-Charon', gcloud: true },
    'en-US-Chirp3-HD-Fenrir': { label: 'en-US-Chirp3-HD-Fenrir', gcloud: true },
    'en-US-Chirp3-HD-Kore': { label: 'en-US-Chirp3-HD-Kore', gcloud: true },
    'en-US-Chirp3-HD-Leda': { label: 'en-US-Chirp3-HD-Leda', gcloud: true },
    'en-US-Chirp3-HD-Orus': { label: 'en-US-Chirp3-HD-Orus', gcloud: true },
    'en-US-Chirp3-HD-Puck': { label: 'en-US-Chirp3-HD-Puck', gcloud: true },
    'en-US-Chirp3-HD-Zephyr': { label: 'en-US-Chirp3-HD-Zephyr', gcloud: true },
    'en-US-Chirp3-HD-Sulafat': { label: 'en-US-Chirp3-HD-Sulafat', gcloud: true },
    'en-US-Chirp3-HD-Achernar': { label: 'en-US-Chirp3-HD-Achernar', gcloud: true },
    'en-US-Neural2-A': { label: 'en-US-Neural2-A', gcloud: true },
    'en-US-Neural2-C': { label: 'en-US-Neural2-C', gcloud: true },
    'en-US-Neural2-D': { label: 'en-US-Neural2-D', gcloud: true },
    'en-US-Neural2-F': { label: 'en-US-Neural2-F', gcloud: true },
    'en-US-Neural2-G': { label: 'en-US-Neural2-G', gcloud: true },
    'en-US-Neural2-H': { label: 'en-US-Neural2-H', gcloud: true },
    'en-US-Neural2-I': { label: 'en-US-Neural2-I', gcloud: true },
    'en-US-Neural2-J': { label: 'en-US-Neural2-J', gcloud: true },
    'en-US-Wavenet-A': { label: 'en-US-Wavenet-A', gcloud: true },
    'en-US-Wavenet-C': { label: 'en-US-Wavenet-C', gcloud: true },
    'en-US-Wavenet-D': { label: 'en-US-Wavenet-D', gcloud: true },
    'en-US-Wavenet-F': { label: 'en-US-Wavenet-F', gcloud: true },

    'en-GB-Studio-B': { label: 'en-GB-Studio-B', gcloud: true },
    'en-GB-Studio-C': { label: 'en-GB-Studio-C', gcloud: true },
    'en-GB-Chirp-HD-A': { label: 'en-GB-Chirp-HD-A', gcloud: true },
    'en-GB-Chirp-HD-B': { label: 'en-GB-Chirp-HD-B', gcloud: true },
    'en-GB-Chirp-HD-C': { label: 'en-GB-Chirp-HD-C', gcloud: true },
    'en-GB-Chirp-HD-D': { label: 'worrington nessa', gcloud: true },
    'en-GB-Chirp-HD-F': { label: 'en-GB-Chirp-HD-F', gcloud: true },
    'en-GB-Neural2-A': { label: 'en-GB-Neural2-A', gcloud: true },
    'en-GB-Neural2-B': { label: 'en-GB-Neural2-B', gcloud: true },
    'en-GB-Neural2-C': { label: 'en-GB-Neural2-C', gcloud: true },
    'en-GB-Neural2-D': { label: 'en-GB-Neural2-D', gcloud: true },
    'en-GB-Neural2-F': { label: 'en-GB-Neural2-F', gcloud: true },
    'en-GB-Wavenet-A': { label: 'en-GB-Wavenet-A', gcloud: true },
    'en-GB-Wavenet-B': { label: 'en-GB-Wavenet-B', gcloud: true },
    'en-GB-Wavenet-C': { label: 'en-GB-Wavenet-C', gcloud: true },
    'en-GB-Wavenet-D': { label: 'en-GB-Wavenet-D', gcloud: true },
    'en-GB-Wavenet-F': { label: 'en-GB-Wavenet-F', gcloud: true },

    'en-AU-Neural2-A': { label: 'en-AU-Neural2-A', gcloud: true },
    'en-AU-Neural2-B': { label: 'en-AU-Neural2-B', gcloud: true },
    'en-AU-Neural2-C': { label: 'en-AU-Neural2-C', gcloud: true },
    'en-AU-Neural2-D': { label: 'en-AU-Neural2-D', gcloud: true },
    'en-AU-Wavenet-A': { label: 'en-AU-Wavenet-A', gcloud: true },
    'en-AU-Wavenet-B': { label: 'en-AU-Wavenet-B', gcloud: true },
    'en-AU-Wavenet-C': { label: 'en-AU-Wavenet-C', gcloud: true },
    'en-AU-Wavenet-D': { label: 'en-AU-Wavenet-D', gcloud: true },

    'en-IN-Neural2-A': { label: 'en-IN-Neural2-A', gcloud: true },
    'en-IN-Neural2-B': { label: 'en-IN-Neural2-B', gcloud: true },
    'en-IN-Neural2-C': { label: 'en-IN-Neural2-C', gcloud: true },
    'en-IN-Neural2-D': { label: 'en-IN-Neural2-D', gcloud: true },
    'en-IN-Wavenet-A': { label: 'en-IN-Wavenet-A', gcloud: true },
    'en-IN-Wavenet-B': { label: 'en-IN-Wavenet-B', gcloud: true },
    'en-IN-Wavenet-C': { label: 'en-IN-Wavenet-C', gcloud: true },
    'en-IN-Wavenet-D': { label: 'en-IN-Wavenet-D', gcloud: true },

    // --- Gemini TTS (Preview) ---
    'gemini-Puck': { label: '♊ Gemini Puck (Male)', gemini: true, voiceKey: 'Puck' },
    'gemini-Charon': { label: '♊ Gemini Charon (Male)', gemini: true, voiceKey: 'Charon' },
    'gemini-Kore': { label: '♊ Gemini Kore (Female)', gemini: true, voiceKey: 'Kore' },
    'gemini-Fenrir': { label: '♊ Gemini Fenrir (Male)', gemini: true, voiceKey: 'Fenrir' },
    'gemini-Aoede': { label: '♊ Gemini Aoede (Female)', gemini: true, voiceKey: 'Aoede' },
    'gemini-Achernar': { label: '♊ Gemini Achernar (Female)', gemini: true, voiceKey: 'Achernar' },
    'gemini-Achird': { label: '♊ Gemini Achird', gemini: true, voiceKey: 'Achird' },
    'gemini-Algenib': { label: '♊ Gemini Algenib', gemini: true, voiceKey: 'Algenib' },
    'gemini-Algieba': { label: '♊ Gemini Algieba', gemini: true, voiceKey: 'Algieba' },
    'gemini-Alnilam': { label: '♊ Gemini Alnilam', gemini: true, voiceKey: 'Alnilam' },
    'gemini-Autonoe': { label: '♊ Gemini Autonoe', gemini: true, voiceKey: 'Autonoe' },
    'gemini-Callirrhoe': { label: '♊ Gemini Callirrhoe', gemini: true, voiceKey: 'Callirrhoe' },
    'gemini-Despina': { label: '♊ Gemini Despina', gemini: true, voiceKey: 'Despina' },
    'gemini-Enceladus': { label: '♊ Gemini Enceladus (Male)', gemini: true, voiceKey: 'Enceladus' },
    'gemini-Erinome': { label: '♊ Gemini Erinome', gemini: true, voiceKey: 'Erinome' },
    'gemini-Gacrux': { label: '♊ Gemini Gacrux', gemini: true, voiceKey: 'Gacrux' },
    'gemini-Iapetus': { label: '♊ Gemini Iapetus (Male)', gemini: true, voiceKey: 'Iapetus' },
    'gemini-Laomedeia': { label: '♊ Gemini Laomedeia', gemini: true, voiceKey: 'Laomedeia' },
    'gemini-Leda': { label: '♊ Gemini Leda (Female)', gemini: true, voiceKey: 'Leda' },
    'gemini-Orus': { label: '♊ Gemini Orus (Male)', gemini: true, voiceKey: 'Orus' },
    'gemini-Pulcherrima': { label: '♊ Gemini Pulcherrima', gemini: true, voiceKey: 'Pulcherrima' },
    'gemini-Rasalgethi': { label: '♊ Gemini Rasalgethi', gemini: true, voiceKey: 'Rasalgethi' },
    'gemini-Sadachbia': { label: '♊ Gemini Sadachbia', gemini: true, voiceKey: 'Sadachbia' },
    'gemini-Sadaltager': { label: '♊ Gemini Sadaltager', gemini: true, voiceKey: 'Sadaltager' },
    'gemini-Schedar': { label: '♊ Gemini Schedar', gemini: true, voiceKey: 'Schedar' },
    'gemini-Sulafat': { label: '♊ Gemini Sulafat (Female)', gemini: true, voiceKey: 'Sulafat' },
    'gemini-Umbriel': { label: '♊ Gemini Umbriel', gemini: true, voiceKey: 'Umbriel' },
    'gemini-Vindemiatrix': { label: '♊ Gemini Vindemiatrix', gemini: true, voiceKey: 'Vindemiatrix' },
    'gemini-Zephyr': { label: '♊ Gemini Zephyr (Female)', gemini: true, voiceKey: 'Zephyr' },
    'gemini-Zubenelgenubi': { label: '♊ Gemini Zubenelgenubi', gemini: true, voiceKey: 'Zubenelgenubi' },

    // --- Amazon Polly ---
    'polly-generative-Ruth': { label: 'Amazon Polly - Ruth (Generative, Female)', polly: true, engine: 'generative', voiceId: 'Ruth' },
    'polly-generative-Matthew': { label: 'Amazon Polly - Matthew (Generative, Male)', polly: true, engine: 'generative', voiceId: 'Matthew' },
    'polly-generative-Amy': { label: 'Amazon Polly - Amy (Generative, Female, UK)', polly: true, engine: 'generative', voiceId: 'Amy' },
    'polly-neural-Joanna': { label: 'Amazon Polly - Joanna (Neural, Female)', polly: true, engine: 'neural', voiceId: 'Joanna' },
    'polly-neural-Matthew': { label: 'Amazon Polly - Matthew (Neural, Male)', polly: true, engine: 'neural', voiceId: 'Matthew' },
    'polly-neural-Kendra': { label: 'Amazon Polly - Kendra (Neural, Female)', polly: true, engine: 'neural', voiceId: 'Kendra' },
    'polly-neural-Brian': { label: 'Amazon Polly - Brian (Neural, Male, UK)', polly: true, engine: 'neural', voiceId: 'Brian' },
    'polly-standard-Salli': { label: 'Amazon Polly - Salli (Standard, Female)', polly: true, engine: 'standard', voiceId: 'Salli' },
    'polly-standard-Joey': { label: 'Amazon Polly - Joey (Standard, Male)', polly: true, engine: 'standard', voiceId: 'Joey' },
    'polly-standard-Ivy': { label: 'Amazon Polly - Ivy (Standard, Female, Child)', polly: true, engine: 'standard', voiceId: 'Ivy' }
};
