module.exports = {
    // Free Google Translate (Legacy)
    'en-US': { label: 'en-US (Google Translate)', lang: 'en', host: 'https://translate.google.com' },
    'en-GB': { label: 'en-GB (Google Translate)', lang: 'en', host: 'https://translate.google.co.uk' },
    'en-AU': { label: 'en-AU (Google Translate)', lang: 'en', host: 'https://translate.google.com.au' },
    'en-IN': { label: 'en-IN (Google Translate)', lang: 'en', host: 'https://translate.google.co.in' },
    'es-ES': { label: 'es-ES (Google Translate)', lang: 'es', host: 'https://translate.google.com' },
    'fr-FR': { label: 'fr-FR (Google Translate)', lang: 'fr', host: 'https://translate.google.com' },
    'ja-JP': { label: 'ja-JP (Google Translate)', lang: 'ja', host: 'https://translate.google.com' },
    'de-DE': { label: 'de-DE (Google Translate)', lang: 'de', host: 'https://translate.google.com' },
    'pt-BR': { label: 'pt-BR (Google Translate)', lang: 'pt', host: 'https://translate.google.com' },

    // --- Google Cloud (Official) ---
    'en-US-Studio-O': { label: 'en-US-Studio-O', gcloud: true },
    'en-US-Chirp3-HD-Aoede': { label: 'en-US-Chirp3-HD-Aoede', gcloud: true },
    'en-US-Chirp3-HD-Charon': { label: 'en-US-Chirp3-HD-Charon', gcloud: true },
    'en-US-Chirp3-HD-Fenrir': { label: 'en-US-Chirp3-HD-Fenrir', gcloud: true },
    'en-US-Chirp3-HD-Kore': { label: 'en-US-Chirp3-HD-Kore', gcloud: true },
    'en-US-Chirp3-HD-Leda': { label: 'en-US-Chirp3-HD-Leda', gcloud: true },
    'en-US-Chirp3-HD-Orus': { label: 'en-US-Chirp3-HD-Orus', gcloud: true },
    'en-US-Chirp3-HD-Puck': { label: 'en-US-Chirp3-HD-Puck', gcloud: true },
    'en-US-Chirp3-HD-Zephyr': { label: 'en-US-Chirp3-HD-Zephyr', gcloud: true },
    'en-US-Chirp3-HD-Sulafat': { label: 'en-US-Chirp3-HD-Sulafat', gcloud: true },
    'en-US-Chirp3-HD-Achernar': { label: 'en-US-Chirp3-HD-Achernar', gcloud: true },
    'en-US-Neural2-A': { label: 'en-US-Neural2-A', gcloud: true },
    'en-US-Neural2-C': { label: 'en-US-Neural2-C', gcloud: true },
    'en-US-Neural2-D': { label: 'en-US-Neural2-D', gcloud: true },
    'en-US-Neural2-F': { label: 'en-US-Neural2-F', gcloud: true },
    'en-US-Neural2-G': { label: 'en-US-Neural2-G', gcloud: true },
    'en-US-Neural2-H': { label: 'en-US-Neural2-H', gcloud: true },
    'en-US-Neural2-I': { label: 'en-US-Neural2-I', gcloud: true },
    'en-US-Neural2-J': { label: 'en-US-Neural2-J', gcloud: true },
    'en-US-Wavenet-A': { label: 'en-US-Wavenet-A', gcloud: true },
    'en-US-Wavenet-C': { label: 'en-US-Wavenet-C', gcloud: true },
    'en-US-Wavenet-D': { label: 'en-US-Wavenet-D', gcloud: true },
    'en-US-Wavenet-F': { label: 'en-US-Wavenet-F', gcloud: true },

    'en-GB-Studio-B': { label: 'en-GB-Studio-B', gcloud: true },
    'en-GB-Studio-C': { label: 'en-GB-Studio-C', gcloud: true },
    'en-GB-Chirp-HD-A': { label: 'en-GB-Chirp-HD-A', gcloud: true },
    'en-GB-Chirp-HD-B': { label: 'en-GB-Chirp-HD-B', gcloud: true },
    'en-GB-Chirp-HD-C': { label: 'en-GB-Chirp-HD-C', gcloud: true },
    'en-GB-Chirp-HD-D': { label: 'worrington nessa', gcloud: true },
    'en-GB-Chirp-HD-F': { label: 'en-GB-Chirp-HD-F', gcloud: true },
    'en-GB-Neural2-A': { label: 'en-GB-Neural2-A', gcloud: true },
    'en-GB-Neural2-B': { label: 'en-GB-Neural2-B', gcloud: true },
    'en-GB-Neural2-C': { label: 'en-GB-Neural2-C', gcloud: true },
    'en-GB-Neural2-D': { label: 'en-GB-Neural2-D', gcloud: true },
    'en-GB-Neural2-F': { label: 'en-GB-Neural2-F', gcloud: true },
    'en-GB-Wavenet-A': { label: 'en-GB-Wavenet-A', gcloud: true },
    'en-GB-Wavenet-B': { label: 'en-GB-Wavenet-B', gcloud: true },
    'en-GB-Wavenet-C': { label: 'en-GB-Wavenet-C', gcloud: true },
    'en-GB-Wavenet-D': { label: 'en-GB-Wavenet-D', gcloud: true },
    'en-GB-Wavenet-F': { label: 'en-GB-Wavenet-F', gcloud: true },

    'en-AU-Neural2-A': { label: 'en-AU-Neural2-A', gcloud: true },
    'en-AU-Neural2-B': { label: 'en-AU-Neural2-B', gcloud: true },
    'en-AU-Neural2-C': { label: 'en-AU-Neural2-C', gcloud: true },
    'en-AU-Neural2-D': { label: 'en-AU-Neural2-D', gcloud: true },
    'en-AU-Wavenet-A': { label: 'en-AU-Wavenet-A', gcloud: true },
    'en-AU-Wavenet-B': { label: 'en-AU-Wavenet-B', gcloud: true },
    'en-AU-Wavenet-C': { label: 'en-AU-Wavenet-C', gcloud: true },
    'en-AU-Wavenet-D': { label: 'en-AU-Wavenet-D', gcloud: true },

    'en-IN-Neural2-A': { label: 'en-IN-Neural2-A', gcloud: true },
    'en-IN-Neural2-B': { label: 'en-IN-Neural2-B', gcloud: true },
    'en-IN-Neural2-C': { label: 'en-IN-Neural2-C', gcloud: true },
    'en-IN-Neural2-D': { label: 'en-IN-Neural2-D', gcloud: true },
    'en-IN-Wavenet-A': { label: 'en-IN-Wavenet-A', gcloud: true },
    'en-IN-Wavenet-B': { label: 'en-IN-Wavenet-B', gcloud: true },
    'en-IN-Wavenet-C': { label: 'en-IN-Wavenet-C', gcloud: true },
    'en-IN-Wavenet-D': { label: 'en-IN-Wavenet-D', gcloud: true },

    // --- Gemini TTS (Preview) ---
    'gemini-Aoede': { label: '♊ Gemini Aoede', gemini: true, voiceKey: 'Aoede' },
    'gemini-Puck': { label: '♊ Gemini Puck', gemini: true, voiceKey: 'Puck' },
    'gemini-Zephyr': { label: '♊ Gemini Zephyr', gemini: true, voiceKey: 'Zephyr' },
    'gemini-Charon': { label: '♊ Gemini Charon', gemini: true, voiceKey: 'Charon' },
    'gemini-Fenrir': { label: '♊ Gemini Fenrir', gemini: true, voiceKey: 'Fenrir' },
    'gemini-Kore': { label: '♊ Gemini Kore', gemini: true, voiceKey: 'Kore' },
    'gemini-Leda': { label: '♊ Gemini Leda', gemini: true, voiceKey: 'Leda' },
    'gemini-Orus': { label: '♊ Gemini Orus', gemini: true, voiceKey: 'Orus' },
    'gemini-Achernar': { label: '♊ Gemini Achernar', gemini: true, voiceKey: 'Achernar' },
    'gemini-Sulafat': { label: '♊ Gemini Sulafat', gemini: true, voiceKey: 'Sulafat' },
    'gemini-Enceladus': { label: '♊ Gemini Enceladus', gemini: true, voiceKey: 'Enceladus' },
    'gemini-Iapetus': { label: '♊ Gemini Iapetus', gemini: true, voiceKey: 'Iapetus' }
};
